{
  "Uuid": "ff7cf585-0c8f-4fee-9a72-7f0163e6fac7",
  "IsCustomNode": false,
  "Description": null,
  "Name": "PrismSolidConstruction",
  "ElementResolver": {
    "ResolutionMap": {}
  },
  "Inputs": [],
  "Outputs": [],
  "Nodes": [
    {
      "ConcreteType": "Dynamo.Graph.Nodes.CustomNodes.Function, DynamoCore",
      "FunctionSignature": "3ed90547-6af2-4cd0-b0bf-da909066faa8",
      "FunctionType": "Graph",
      "NodeType": "FunctionNode",
      "Id": "447e2b33f9be4ef8b9e881fc543a0a37",
      "Inputs": [
        {
          "Id": "f8f0780d9a5c4c31a08196122bf6d399",
          "Name": "toggle",
          "Description": "bool\nDefault value : true",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "2bf678329f1a448195692831f5ce5110",
          "Name": "descriptions",
          "Description": "return value",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "930ace81499d4b2fab546895cd4970c4",
          "Name": "elements",
          "Description": "return value",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "fe0c7121ae2e4579a4ae4b3ecb007f22",
          "Name": "warnings",
          "Description": "return value",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": ""
    },
    {
      "ConcreteType": "PythonNodeModels.PythonNode, PythonNodeModels",
      "NodeType": "PythonScriptNode",
      "Code": "#Based on\r\n#https://thebuildingcoder.typepad.com/blog/2015/07/intersect-solid-filter-avf-and-directshape-for-debugging.html\r\n\r\nimport clr\r\nclr.AddReference(\"RevitServices\")\r\nimport RevitServices\r\nfrom RevitServices.Persistence import DocumentManager\r\n\r\nclr.AddReference('ProtoGeometry')\r\nfrom Autodesk.DesignScript.Geometry import *\r\n\r\n# Import ToDSType(bool) extension method\r\nclr.AddReference('RevitNodes')\r\nimport Revit\r\nclr.ImportExtensions(Revit.Elements)\r\n# Import ToProtoType() extension method\r\nclr.ImportExtensions(Revit.GeometryConversion)\r\n\r\nclr.AddReference(\"RevitAPI\")\r\nclr.AddReference(\"RevitAPIUI\")\r\nimport Autodesk\r\nfrom Autodesk.Revit.UI import *\r\nfrom Autodesk.Revit.DB import *\r\n\r\nfrom System.Collections.Generic import *\r\n\r\n\r\ndef CreateCube(d):\r\n\treturn CreateRectangularPrism(XYZ.Zero, d, d, d)\r\n\t\r\n\t\r\ndef CreateRectangularPrism(center, d1, d2, d3): \r\n\r\n    profile = []\r\n    \r\n    profile00 = XYZ(-d1/2, -d2/2, -d3/2)\r\n    profile01 = XYZ(-d1/2,  d2/2, -d3/2)\r\n    profile11 = XYZ( d1/2,  d2/2, -d3/2)\r\n    profile10 = XYZ( d1/2, -d2/2, -d3/2)\r\n    \r\n    profile.Add(Line.CreateBound(profile00, profile01))\r\n    profile.Add(Line.CreateBound(profile01, profile11))\r\n    profile.Add(Line.CreateBound(profile11, profile10))\r\n    profile.Add(Line.CreateBound(profile10, profile00))\r\n    \r\n    curveLoop = [CurveLoop.Create(profile)]\r\n    \r\n    options = SolidOptions(ElementId.InvalidElementId, ElementId.InvalidElementId)\r\n    \r\n    return GeometryCreationUtilities.CreateExtrusionGeometry(curveLoop, XYZ.BasisZ, d3, options)\r\n    \r\n\r\n#doc = DocumentManager.Instance.CurrentDBDocument\r\nsolid = CreateCube(100)\r\n\r\n\r\nOUT = solid.ToProtoType(), dir(solid)",
      "VariableInputPorts": true,
      "Id": "2410d1589571469eb42ac9c0d486554e",
      "Inputs": [
        {
          "Id": "f5535506f9b24a179f4332153159a62e",
          "Name": "IN[0]",
          "Description": "Input #0",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "dc14ae1a6425487faa7a1fd693248be0",
          "Name": "OUT",
          "Description": "Result of the python script",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled",
      "Description": "Runs an embedded IronPython script."
    }
  ],
  "Connectors": [],
  "Dependencies": [
    "3ed90547-6af2-4cd0-b0bf-da909066faa8"
  ],
  "Bindings": [],
  "View": {
    "Dynamo": {
      "ScaleFactor": 1.0,
      "HasRunWithoutCrash": true,
      "IsVisibleInDynamoLibrary": true,
      "Version": "2.0.1.5055",
      "RunType": "Manual",
      "RunPeriod": "1000"
    },
    "Camera": {
      "Name": "Background Preview",
      "EyeX": -75196.918434428619,
      "EyeY": 81126.821454026751,
      "EyeZ": -100478.92245645206,
      "LookX": 75196.918434428619,
      "LookY": -81126.821454026751,
      "LookZ": 100478.92245645206,
      "UpX": 0.20983451245275969,
      "UpY": 0.9366721892483989,
      "UpZ": 0.280383108036713
    },
    "NodeViews": [
      {
        "ShowGeometry": true,
        "Name": "Warnings",
        "Id": "447e2b33f9be4ef8b9e881fc543a0a37",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 626.5,
        "Y": 288.0
      },
      {
        "ShowGeometry": true,
        "Name": "Python Script",
        "Id": "2410d1589571469eb42ac9c0d486554e",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 941.82849772104009,
        "Y": 285.6958924318464
      }
    ],
    "Annotations": [],
    "X": -642.94402367626344,
    "Y": 7.0490965965216219,
    "Zoom": 1.3815320522883234
  }
}